In [45]:
import pandas as pd
from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

df = pd.read_excel("ComprasClean.xlsx", index_col = "Unnamed: 0")
df.head()

,Cod_Producto,id_Proveedor,id_Sucursal,Cod_Bodega,Cod_Unidad_Negocio,ano_Orden,mes_Orden,dia_Orden,Compra_Cantidad,Compra_Pesos,Compra_Precio_Unitario,Linea_a_Tiempo,Linea_Completa,Lead_Time_Teorico_Compra,Lead_Time_Real_Max_Compra,Conteo_Linea_Compra,Recepcion_Max_Fecha_Real
0,10403,387,1,71,4,2018,5,11,6,405072,67512,0,1,10,34,1,20180614
1,10403,387,1,71,4,2018,1,26,12,770160,64180,0,1,10,11,1,20180206
2,10403,387,1,71,4,2018,4,23,21,1417752,67512,0,1,10,16,1,20180509
3,10318,387,1,71,4,2018,4,23,6,555000,92500,0,1,10,16,1,20180509
4,10403,387,1,71,4,2018,5,4,25,1687800,67512,0,1,10,41,1,20180614

In [46]:
infoProduct = (df.groupby(["id_Proveedor","Cod_Producto"])["Compra_Cantidad"].sum().unstack().reset_index().fillna(0).set_index("id_Proveedor")) 
infoProduct

Cod_Producto,3639,4455,5106,5109,5110,6507,10318,10390,10396,10401,...,39568,39632,39633,39733,39735,39741,39783,39933,39934,40428
id_Proveedor,,,,,,,,,,,,,,,,,,,,,
9,4188300.0,1676000.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
10,0.0,0.0,61630.0,42378.0,59321.0,0.0,0.0,0.0,0.0,0.0,...,0.0,4245.0,2668.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
228,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
349,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
373,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
386,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,2551.0,0.0,0.0,1577.0,1235.0,1102.0,3141.0,10035.0,1727.0,1334.0
387,0.0,0.0,0.0,0.0,0.0,0.0,8817.0,6872.0,10530.0,67526.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
391,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
392,0.0,0.0,0.0,0.0,0.0,114309.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
11837,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
21278,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25749,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
25865,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
27152,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0

In [47]:
def binarizar(x):
    if x <= 0:
        return 0
    if x >= 1:
        return 1
dfMatriz = infoProduct.applymap(binarizar)
dfMatriz

Cod_Producto,3639,4455,5106,5109,5110,6507,10318,10390,10396,10401,...,39568,39632,39633,39733,39735,39741,39783,39933,39934,40428
id_Proveedor,,,,,,,,,,,,,,,,,,,,,
9,1,1,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
10,0,0,1,1,1,0,0,0,0,0,...,0,1,1,0,0,0,0,0,0,0
228,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
349,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
373,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
386,0,0,0,0,0,0,0,0,0,0,...,1,0,0,1,1,1,1,1,1,1
387,0,0,0,0,0,0,1,1,1,1,...,0,0,0,0,0,0,0,0,0,0
391,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
392,0,0,0,0,0,1,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
11837,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
21278,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25749,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
25865,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0
27152,0,0,0,0,0,0,0,0,0,0,...,0,0,0,0,0,0,0,0,0,0

In [52]:
frecuencia = apriori(dfMatriz, min_support = 0.07, use_colnames = True)
reglas = association_rules(frecuencia, metric= "lift", min_threshold = 1)
reglas

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(4455),(3639),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
1,(3639),(4455),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
2,(35394),(3639),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
3,(3639),(35394),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
4,(35394),(4455),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
5,(4455),(35394),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
6,(5106),(5109),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
7,(5109),(5106),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
8,(5106),(5110),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
9,(5110),(5106),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
10,(39632),(5106),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
11,(5106),(39632),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
12,(39633),(5106),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
13,(5106),(39633),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
14,(5109),(5110),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
15,(5110),(5109),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
16,(39632),(5109),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
17,(5109),(39632),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
18,(39633),(5109),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
19,(5109),(39633),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
20,(39632),(5110),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
21,(5110),(39632),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
22,(39633),(5110),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
23,(5110),(39633),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
24,(28955),(6507),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
25,(6507),(28955),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
26,(6507),(34598),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
27,(34598),(6507),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
28,(6507),(35412),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
29,(35412),(6507),0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
...,...,...,...,...,...,...,...,...,...
59344,"(28364, 39933)","(39783, 39431, 40428, 39568, 39733, 39735, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59345,"(28364, 39733)","(39783, 39431, 39741, 40428, 39568, 39735, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59346,"(28364, 39735)","(39783, 39431, 39741, 40428, 39568, 39733, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59347,"(28364, 39741)","(39783, 39431, 40428, 39568, 39733, 39735, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59348,"(28364, 39934)","(39783, 39431, 39741, 40428, 39568, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59349,"(39568, 39933)","(39783, 39431, 28364, 40428, 39733, 39735, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59350,"(39568, 39733)","(39783, 39431, 39741, 28364, 40428, 39735, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59351,"(39568, 39735)","(39783, 39431, 39741, 28364, 40428, 39733, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59352,"(39568, 39741)","(39783, 39431, 28364, 40428, 39733, 39735, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59353,"(39568, 39934)","(39783, 39431, 39741, 28364, 40428, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59354,"(39733, 39933)","(39783, 39431, 28364, 40428, 39568, 39735, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59355,"(39933, 39735)","(39783, 39431, 28364, 40428, 39568, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59356,"(39741, 39933)","(39783, 39431, 28364, 40428, 39568, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59357,"(39933, 39934)","(39783, 39431, 28364, 40428, 39568, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59358,"(39733, 39735)","(39783, 39431, 39741, 28364, 40428, 39568, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59359,"(39741, 39733)","(39783, 39431, 28364, 40428, 39568, 39735, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59360,"(39733, 39934)","(39783, 39431, 39741, 28364, 40428, 39568, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59361,"(39741, 39735)","(39783, 39431, 28364, 40428, 39568, 39733, 399...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59362,"(39934, 39735)","(39783, 39431, 39741, 28364, 40428, 39568, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59363,"(39741, 39934)","(39783, 39431, 28364, 40428, 39568, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59364,(39431),"(39783, 40428, 28364, 39568, 39933, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59365,(39783),"(39431, 40428, 28364, 39568, 39933, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59366,(40428),"(39431, 39783, 28364, 39568, 39933, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59367,(28364),"(39431, 39783, 40428, 39568, 39933, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59368,(39568),"(39431, 39783, 40428, 28364, 39933, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59369,(39933),"(39431, 39783, 40428, 28364, 39568, 39733, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59370,(39733),"(39431, 39783, 40428, 28364, 39568, 39933, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59371,(39735),"(39431, 39783, 40428, 28364, 39568, 39933, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59372,(39741),"(39431, 39783, 40428, 28364, 39568, 39933, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf
59373,(39934),"(39431, 39783, 40428, 28364, 39568, 39933, 397...",0.071429,0.071429,0.071429,1.0,14.0,0.066327,inf